Repository ZolaApp/zola-app, pull requests merged in 2018-05, with the labels that each got.

#37 Add styled-components setup
  .babelrc
  jsconfig.json
  next.config.js
  package-lock.json
  package.json
  src/components/Button/index.js
  src/components/Button/styles.js
  src/components/Input/index.js
  src/components/Input/styles.js
  src/components/InputWithLabel/index.js
  src/components/InputWithLabel/styles.js
  src/components/Link/index.js
  src/components/Link/styles.js
  src/components/RegistrationForm/index.js
  src/components/RegistrationForm/styles.js
  src/components/RegistrationHeader/index.js
  src/components/RegistrationHeader/styles.js
  src/components/Text/index.js
  src/components/Wrapper/index.js
  src/pages/_app.js
  src/pages/_document.js
  src/pages/register.js
  src/styles/reset.css
  src/styles/style.css
  src/styles/theme.js
Labels: WIP

#34 Add flow-typed and babel-plugin-inline-import-graphql-ast dev dependencies
  .babelrc
  .flowconfig
  package-lock.json
  package.json
Labels: Chore

#54 Remove duplicate dependency & run flow-typed install
  .eslintignore
  flow-typed/npm/@zeit/next-css_vx.x.x.js
  flow-typed/npm/babel-eslint_vx.x.x.js
  flow-typed/npm/babel-plugin-module-resolver_vx.x.x.js
  flow-typed/npm/babel-plugin-styled-components_vx.x.x.js
  flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x.js
  flow-typed/npm/eslint-config-prettier_vx.x.x.js
  flow-typed/npm/eslint-config-standard-react_vx.x.x.js
  flow-typed/npm/eslint-config-standard_vx.x.x.js
  flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js
  flow-typed/npm/eslint-plugin-import_vx.x.x.js
  flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js
  flow-typed/npm/eslint-plugin-node_vx.x.x.js
  flow-typed/npm/eslint-plugin-promise_vx.x.x.js
  flow-typed/npm/eslint-plugin-react_vx.x.x.js
  flow-typed/npm/eslint-plugin-standard_vx.x.x.js
  flow-typed/npm/eslint_vx.x.x.js
  flow-typed/npm/flow-bin_v0.x.x.js
  flow-typed/npm/husky_vx.x.x.js
  flow-typed/npm/lint-staged_vx.x.x.js
  flow-typed/npm/next_vx.x.x.js
  flow-typed/npm/prettier_v1.x.x.js
  flow-typed/npm/styled-components_v3.x.x.js
  package-lock.json
  package.json
Labels: Chore

#56 Set up ApolloClient
  .babelrc
  .env.dist
  .gitignore
  env.config.js
  flow-typed/npm/apollo-boost_vx.x.x.js
  flow-typed/npm/isomorphic-unfetch_vx.x.x.js
  flow-typed/npm/next-compose-plugins_vx.x.x.js
  flow-typed/npm/next-optimized-images_vx.x.x.js
  flow-typed/npm/react-apollo_v2.x.x.js
  flow-typed/npm/spritesh_vx.x.x.js
  flow-typed/npm/svgo_vx.x.x.js
  flow-typed/process.js
  jsconfig.json
  next.config.js
  package-lock.json
  package.json
  src/higherOrders/withApolloClient/index.js
  src/higherOrders/withApolloClient/initApollo.js
  src/pages/_app.js
Labels: Feature

#57 Implement Register mutation
  .babelrc
  package-lock.json
  package.json
  src/components/Button/styles.js
  src/components/Input/index.js
  src/components/RegistrationForm/index.js
  src/containers/RegistrationForm/index.js
  src/containers/RegistrationForm/mutation.graphql
  src/pages/register.js
Labels: Feature

#62 Pass down environment variables using .babelrc.js
  .babelrc
  .babelrc.js
  env.config.js
Labels: Chore

#69 Add page transitions
  package-lock.json
  package.json
  src/components/LoginForm/index.js
  src/pages/_app.js
  src/styles/style.css
Labels: Feature

#68 Fix React/Next warnings in console
  .eslintrc
  package-lock.json
  package.json
  src/components/Loader/index.js
  src/components/LoginForm/index.js
  src/components/RegistrationForm/index.js
  src/components/Text/index.js
  src/components/Wrapper/index.js
  src/pages/_app.js
  src/pages/_document.js
  src/styles/style.css
Labels: Bug

#67 Handle register success
  .eslintrc
  package-lock.json
  package.json
  src/components/Loader/index.js
  src/components/LoginForm/index.js
  src/components/LoginHeader/index.js
  src/components/RegistrationForm/index.js
  src/components/Text/index.js
  src/components/Wrapper/index.js
  src/containers/RegistrationForm/index.js
  src/pages/_app.js
  src/pages/_document.js
  src/styles/style.css
Labels: Feature

#66 Add Loader to button when `prop.isLoading` is `true`
  .eslintrc
  package-lock.json
  package.json
  src/components/Button/index.js
  src/components/Button/styles.js
  src/components/Loader/index.js
  src/components/LoginForm/index.js
  src/components/LoginHeader/index.js
  src/components/RegistrationForm/index.js
  src/components/Text/index.js
  src/components/Wrapper/index.js
  src/containers/RegistrationForm/index.js
  src/pages/_app.js
  src/pages/_document.js
  src/styles/style.css
Labels: Improvement

#65 Handle registration errors
  .babelrc.js
  .eslintrc
  jsconfig.json
  package-lock.json
  package.json
  src/components/Button/index.js
  src/components/Button/styles.js
  src/components/Errors/index.js
  src/components/Errors/styles.js
  src/components/Input/index.js
  src/components/Input/styles.js
  src/components/InputWithLabel/index.js
  src/components/InputWithLabel/styles.js
  src/components/Loader/index.js
  src/components/LoginForm/index.js
  src/components/LoginHeader/index.js
  src/components/RegistrationForm/index.js
  src/components/RegistrationForm/styles.js
  src/components/Text/index.js
  src/components/Wrapper/index.js
  src/containers/RegistrationForm/index.js
  src/pages/_app.js
  src/pages/_document.js
  src/styles/style.css
  src/types/ValidationError.js
Labels: Feature

#70 Add progress bar between page changes
  package-lock.json
  package.json
  src/pages/_app.js
  src/styles/style.css
Labels: Feature

#79 Improve authentication setup with higherOrders
  src/helpers/clearAccessToken.js
  src/helpers/getAccessToken.js
  src/helpers/redirectTo.js
  src/higherOrders/withApolloClient/index.js
  src/higherOrders/withApolloClient/initApollo.js
  src/higherOrders/withAuthentication/index.js
  src/higherOrders/withNoAuthentication/index.js
  src/pages/_app.js
  src/pages/index.js
  src/pages/login.js
  src/pages/logout.js
  src/pages/project.js
  src/pages/register.js
Labels: Improvement

#77 Disable Babel’s cache
  next.config.js
  package.json
Labels: Chore

#75 Handle authentication (pt. 2)
  src/helpers/clearAccessToken.js
  src/helpers/getAccessToken.js
  src/helpers/redirectTo.js
  src/higherOrders/withApolloClient/index.js
  src/higherOrders/withApolloClient/initApollo.js
  src/higherOrders/withAuthentication/index.js
  src/higherOrders/withNoAuthentication/index.js
  src/pages/_app.js
  src/pages/index.js
  src/pages/login.js
  src/pages/logout.js
  src/pages/project.js
  src/pages/register.js
Labels: Feature

#74 Handle authentication (pt. 1)
  .babelrc.js
  jsconfig.json
  package-lock.json
  package.json
  src/constants/cookies.js
  src/containers/LoginForm/index.js
  src/containers/RegistrationForm/index.js
  src/helpers/clearAccessToken.js
  src/helpers/getAccessToken.js
  src/helpers/redirectTo.js
  src/higherOrders/withApolloClient/index.js
  src/higherOrders/withApolloClient/initApollo.js
  src/higherOrders/withAuthentication/index.js
  src/higherOrders/withNoAuthentication/index.js
  src/pages/_app.js
  src/pages/index.js
  src/pages/login.js
  src/pages/logout.js
  src/pages/project.js
  src/pages/register.js
Labels: Feature

#85 Add custom server and dynamic routes setup
  .env.dist
  package-lock.json
  package.json
  routes.js
  scripts/build.sh
  scripts/dev.sh
  scripts/icons.sh
  scripts/lint-svg.sh
  scripts/start.sh
  server.js
Labels: Feature

#87 Single project route authorization
  routes.js
  src/components/ProjectList/index.js
  src/components/SingleProjectPage/index.js
  src/containers/LoginFormContainer/index.js
  src/containers/LoginFormContainer/mutation.graphql
  src/containers/RegistrationFormContainer/index.js
  src/containers/RegistrationFormContainer/mutation.graphql
  src/containers/SingleProjectPageContainer/index.js
  src/containers/SingleProjectPageContainer/query.graphql
  src/higherOrders/withAuthentication/index.js
  src/higherOrders/withNoAuthentication/index.js
  src/pages/index.js
  src/pages/login.js
  src/pages/project.js
  src/pages/register.js
Labels: Feature

#91 Fix “document is not defined” error
  src/higherOrders/withApolloClient/index.js
Labels: Bug

#92 Improvements
  src/components/Button/styles.js
  src/components/Wrapper/index.js
  src/containers/SingleProjectPageContainer/index.js
  src/higherOrders/withAuthentication/index.js
  src/higherOrders/withNoAuthentication/index.js
  src/pages/project.js
Labels: Improvement

#99 Add isEven color variant to project & keys rows
  src/components/KeyItem/index.js
  src/components/KeyItem/styles.js
  src/components/KeyList/index.js
  src/components/ProjectRow/index.js
  src/components/ProjectRow/styles.js
  src/components/ProjectsList/index.js
  src/styles/theme.js
Labels: Improvement

#101 Create a re-usable project page layout and make Sidebar items links
  src/components/LocalesPage/index.js
  src/components/ProjectMenu/index.js
  src/components/ProjectMenu/styles.js
  src/components/SingleProjectLayout/index.js
  src/components/SingleProjectPage/index.js
Labels: Feature

#105 Template sidebar
  src/components/ProjectSidebar/index.js
  src/components/ProjectSidebarUser/index.js
  src/components/ProjectSwitcher/index.js
  src/components/SingleProjectLayout/index.js
  src/containers/ProjectSidebarContainer/index.js
  src/containers/ProjectSidebarContainer/query.graphql
  src/types/User.js
Labels: Improvement

#110 Locales page
  src/components/LocalesPage/index.js
  src/components/LocalesPage/styles.js
  src/components/LocalesRow/index.js
  src/components/LocalesRow/styles.js
  src/components/SingleProjectLayout/index.js
  src/containers/LocalesPageContainer/index.js
  src/containers/LocalesPageContainer/query.graphql
  src/types/Locale.js
  src/types/Project.js
Labels: Feature

#108 Fix missingTranslations and newKeys being queried in the wrong container
  src/containers/HomePageContainer/query.graphql
  src/containers/SingleProjectPageContainer/query.graphql
Labels: Feature

#111 Add key creation modal
  package-lock.json
  src/components/Button/styles.js
  src/components/KeyList/index.js
  src/components/KeyList/styles.js
  src/components/KeysFilters/styles.js
  src/components/KeysHeader/index.js
  src/components/KeysHeader/styles.js
  src/components/NewKeyForm/index.js
  src/components/NewKeyModal/index.js
  src/components/SingleProjectPage/index.js
  src/containers/NewKeyModalContainer/index.js
  src/containers/NewKeyModalContainer/mutation.graphql
  src/containers/SingleProjectPageContainer/query.graphql
  src/types/Locale.js
  src/types/Project.js
Labels: Feature

#103 Add project and key creation modals
  package-lock.json
  package.json
  src/components/Button/index.js
  src/components/Button/styles.js
  src/components/Dropdown/index.js
  src/components/DropdownTrigger/index.js
  src/components/KeyList/index.js
  src/components/KeyList/styles.js
  src/components/KeysFilters/index.js
  src/components/KeysFilters/styles.js
  src/components/KeysHeader/index.js
  src/components/KeysHeader/styles.js
  src/components/NewKeyForm/index.js
  src/components/NewKeyModal/index.js
  src/components/NewProjectForm/index.js
  src/components/NewProjectForm/styles.js
  src/components/NewProjectModal/index.js
  src/components/ProjectsHeader/index.js
  src/components/RegistrationForm/index.js
  src/components/SelectDropdown/index.js
  src/components/SelectDropdown/styles.js
  src/components/SingleProjectPage/index.js
  src/containers/NewKeyModalContainer/index.js
  src/containers/NewKeyModalContainer/mutation.graphql
  src/containers/NewProjectModalContainer/index.js
  src/containers/NewProjectModalContainer/mutation.graphql
  src/containers/NewProjectModalContainer/query.graphql
  src/containers/SingleProjectPageContainer/query.graphql
  src/helpers/errorFinder.js
  src/pages/_document.js
  src/styles/style.css
  src/types/Locale.js
  src/types/Project.js
  src/types/SelectOption.js
Labels: Feature

#114 Fix security issues
  package-lock.json
Labels: Chore

#113 Fix #dialog-root throwing an error
  package-lock.json
  package.json
  src/components/ProjectsHeader/index.js
  src/components/SingleProjectPage/index.js
  src/pages/_app.js
  src/pages/_document.js
  src/styles/style.css
Labels: Bug

#115 Fix key prop warning in locale list
  src/components/LocalesPage/index.js
Labels: Bug
