Repository ZolaApp/zola-app, pull requests merged in 2018-06, with the labels that each got.

#124 Add empty state for projects homepage
  src/components/ProjectsHeader/index.js
  src/components/ProjectsList/index.js
  src/components/ProjectsList/styles.js
  src/components/Text/index.js
Labels: Feature

#128 Use new stats field on projects
  src/containers/HomePageContainer/query.graphql
  src/containers/SingleProjectPageContainer/query.graphql
Labels: Bug

#129 Fix icons not working in production
  .babelrc.js
  scripts/icons.sh
  scripts/lint-svg.sh
  src/assets/icons/arrow-down.svg
  src/assets/icons/delete.svg
  src/assets/icons/edit.svg
  src/assets/icons/gear.svg
  src/assets/icons/key.svg
  src/assets/icons/planet.svg
  src/assets/icons/plus.svg
  src/assets/icons/search.svg
  src/assets/icons/tag.svg
  src/assets/icons/tick.svg
  src/components/Icon/index.js
  src/pages/_document.js
  src/static/icons.svg
Labels: Bug

#130 Add keys’ metrics to project single view
  src/components/ProjectsStats/index.js
  src/components/ProjectsStats/styles.js
  src/components/SingleProjectPage/index.js
  src/components/SingleProjectStats/index.js
  src/components/SingleProjectStats/styles.js
  src/components/StatBlock/index.js
  src/components/StatBlock/styles.js
  src/containers/SingleProjectPageContainer/query.graphql
  src/types/Project.js
  src/types/Stats.js
Labels: Feature

#125 Add ability to set a translated value for each key
  src/assets/icons/delete.svg
  src/components/ButtonIcon/styles.js
  src/components/KeyDetails/index.js
  src/components/KeyDetails/styles.js
  src/components/KeyItem/index.js
  src/components/KeyItem/styles.js
  src/components/KeyList/index.js
  src/components/SingleProjectPage/index.js
  src/components/TranslationItem/index.js
  src/components/TranslationItem/styles.js
  src/components/TranslationValueRow/index.js
  src/components/TranslationValueRow/styles.js
  src/containers/SingleProjectPageContainer/query.graphql
  src/containers/TranslationValueRowContainer/index.js
  src/containers/TranslationValueRowContainer/mutation.graphql
  src/static/icons.svg
  src/types/TranslationKey.js
Labels: Feature

#133 Template stats on the homepage
  src/components/HomePage/index.js
  src/components/ProjectRow/index.js
  src/components/ProjectsStats/index.js
  src/components/ProjectsStats/styles.js
  src/components/SingleProjectStats/index.js
  src/containers/HomePageContainer/index.js
  src/containers/HomePageContainer/query.graphql
  src/types/Stats.js
Labels: Feature

#134 Template translation keys row
  src/components/KeyDetails/index.js
  src/components/KeyItem/index.js
  src/components/KeyItem/styles.js
  src/components/Tag/styles.js
  src/containers/SingleProjectPageContainer/query.graphql
  src/containers/TranslationValueRowContainer/index.js
  src/types/TranslationKey.js
Labels: Improvement

#132 Template locales page
  src/components/LocaleRow/index.js
  src/components/LocaleRow/styles.js
  src/components/LocalesPage/index.js
  src/containers/LocalesPageContainer/index.js
  src/containers/LocalesPageContainer/query.graphql
  src/types/Locale.js
Labels: Feature

#139 Template default locale
  src/components/LocaleRow/index.js
  src/components/LocalesPage/index.js
  src/types/Locale.js
Labels: Feature

#140 Improve error handling in key creation modal
  src/containers/NewKeyModalContainer/index.js
Labels: Improvement

#143 Fix stuff
  src/components/KeyList/index.js
  src/components/SingleProjectPage/index.js
  src/containers/SingleProjectPageContainer/query.graphql
  src/types/Project.js
Labels: Bug

#144 Add logout link in sidebar
  src/assets/icons/logout.svg
  src/components/Sidebar/index.js
  src/components/Sidebar/styles.js
  src/static/icons.svg
Labels: Feature

#145 Add favicon
  src/pages/_document.js
  src/static/favicon.png
Labels: Improvement

#136 Add pagination in key list
  package-lock.json
  package.json
  src/assets/icons/download.svg
  src/components/KeyItem/styles.js
  src/components/KeyList/index.js
  src/components/KeyList/styles.js
  src/components/KeyListPaginationBar/index.js
  src/components/KeyListPaginationBar/styles.js
  src/components/Pagination/index.js
  src/components/Pagination/styles.js
  src/components/SingleProjectPage/index.js
  src/constants/pagination.js
  src/containers/SingleProjectPageContainer/index.js
  src/containers/SingleProjectPageContainer/query.graphql
  src/static/icons.svg
Labels: Feature

#149 Fix save button wording in locale creation modal
  src/components/NewLocaleForm/index.js
Labels: Improvement

#148 Remove length limit in locale list
  src/components/NewProjectModal/index.js
Labels: Improvement

#150 Get export keys button to work
  .env.dist
  src/components/KeyList/index.js
  src/components/KeyListPaginationBar/index.js
  src/components/KeyListPaginationBar/styles.js
  src/components/SingleProjectPage/index.js
  src/containers/SingleProjectPageContainer/query.graphql
  src/types/Project.js
Labels: Feature

#147 Add deleteTranslationKey mutation
  src/components/ButtonIcon/index.js
  src/components/KeyItem/index.js
  src/components/KeyList/index.js
  src/components/SingleProjectPage/index.js
  src/constants/pagination.js
  src/containers/KeyItemContainer/index.js
  src/containers/KeyItemContainer/mutation.graphql
  src/containers/NewKeyModalContainer/index.js
  src/containers/NewLocaleModalContainer/index.js
  src/containers/TranslationValueRowContainer/index.js
Labels: Feature

#151 Add missing % for translations complete stat
  src/components/ProjectsStats/index.js
Labels: Improvement

#152 Make sure translation value is not saved when it hasn’t changed
  src/containers/TranslationValueRowContainer/index.js
Labels: Improvement

#153 Add ability to filter keys
  package-lock.json
  package.json
  src/components/KeyItem/styles.js
  src/components/KeysFilters/index.js
  src/components/Pagination/index.js
  src/components/SelectDropdown/index.js
  src/components/SingleProjectPage/index.js
  src/containers/KeyItemContainer/index.js
  src/containers/NewKeyModalContainer/index.js
  src/containers/NewLocaleModalContainer/index.js
  src/containers/SingleProjectPageContainer/index.js
  src/containers/SingleProjectPageContainer/query.graphql
  src/containers/TranslationValueRowContainer/index.js
  src/types/Project.js
Labels: Feature

#160 Don’t refresh the whole page when applying filters
  src/components/KeysFilters/index.js
  src/components/KeysHeader/index.js
Labels: Improvement

#159 Improve toast styles
  src/pages/_app.js
  src/styles/style.css
Labels: Improvement

#163 Improve translation update success feedback
  src/components/Textarea/index.js
  src/components/TranslationValueRow/index.js
  src/components/TranslationValueRow/styles.js
  src/containers/TranslationValueRowContainer/index.js
Labels: Improvement

#162 Hide useless scrollbars
  src/components/SelectDropdown/styles.js
Labels: Improvement

#165 Small UI tweaks
  src/components/ButtonIcon/styles.js
  src/components/SelectDropdown/index.js
  src/components/Textarea/styles.js
Labels: Improvement

#164 Change progress bar styles
  src/styles/style.css
Labels: Improvement

#166 Make font sizes and spacing more consistent across the app
  src/styles/theme.js
Labels: Improvement

#171 Add CDN URL in locales list
  src/components/LocaleRow/index.js
  src/components/LocaleRow/styles.js
  src/components/LocalesPage/index.js
  src/containers/LocalesPageContainer/query.graphql
Labels: Feature

#169 Fix issue with translation row focus
  src/components/TranslationValueRow/index.js
Labels: Bug

#172 Add border-radius to base components
  src/components/DropdownTrigger/styles.js
  src/components/Input/styles.js
  src/components/KeyDetails/styles.js
  src/components/KeyItem/styles.js
  src/components/KeyListPaginationBar/styles.js
  src/components/KeysHeader/styles.js
  src/components/Pagination/styles.js
  src/components/SelectDropdown/styles.js
  src/components/TranslationValueRow/styles.js
Labels: Improvement

#168 Add edit icon on KeyRow
  src/assets/icons/checkbox.svg
  src/assets/icons/edit.svg
  src/components/Icon/index.js
  src/components/Icon/styles.js
  src/components/KeyItem/index.js
  src/components/KeyItem/styles.js
  src/static/icons.svg
Labels: Improvement

#173 Add prefill value feature
  src/components/KeyDetails/index.js
  src/components/PrefillValueAction/index.js
  src/components/PrefillValueAction/styles.js
  src/components/Textarea/index.js
  src/components/TranslationValueRow/index.js
  src/components/TranslationValueRow/styles.js
  src/containers/PrefillValueContainer/index.js
  src/containers/PrefillValueContainer/mutation.graphql
  src/containers/TranslationValueRowContainer/index.js
  src/styles/theme.js
Labels: Feature

#185 Various fixes and improvements
  src/components/KeysFilters/index.js
  src/components/KeysHeader/index.js
  src/components/Pagination/index.js
  src/components/Pagination/styles.js
  src/components/Sidebar/index.js
  src/constants/pagination.js
  src/pages/logout.js
Labels: Bug
